from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1de4c83c38e4'
down_revision: Union[str, Sequence[str], None] = '7a7b7c7d7e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('external_id', sa.String(length=255), nullable=True))
    
    # Добавляем колонки с дефолтными значениями для старых записей
    op.add_column('transactions', sa.Column('payment_method', sa.String(length=20), nullable=False, server_default='sbp'))
    op.add_column('transactions', sa.Column('provider', sa.String(length=50), nullable=False, server_default='platega'))
    
    # Удаляем дефолты после обновления, чтобы новые записи требовали явных значений в модели (по желанию)
    op.alter_column('transactions', 'payment_method', server_default=None)
    op.alter_column('transactions', 'provider', server_default=None)
    
    op.drop_constraint(op.f('transactions_platega_id_key'), 'transactions', type_='unique')
    op.create_unique_constraint(None, 'transactions', ['external_id'])
    op.drop_column('transactions', 'platega_id')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('platega_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='unique')
    op.create_unique_constraint(op.f('transactions_platega_id_key'), 'transactions', ['platega_id'])
    op.drop_column('transactions', 'provider')
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'external_id')
    # ### end Alembic commands ###
